### ISSUE TITLE
Deed give command is not working

### ISSUE THREAD

**Issue by materialplane** [magemonkeystudio/homestead#10]
When I use the /deed give command to give myself a deed I get a notice in chat that says there is no deed found with that name.

I know the names I'm using are correct.

It's not giving me an error when I run the command in the console.

homestead-1.0.1-R2
codex-1.0.1-R0.8

**Comment by Travja** [comment]
The format for `/deed give` is `/deed give <deed_type> [amount] [player]` which is different to most give style commands. I'm not seeing any issues with it that way.
